name: Cypress Testing Workflow
on: [push]

jobs: 
    test:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - name: Greet Me
              run: echo "Hello, GitHub Actions!"
